---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ephemeralapps.toolkit.hinge.com
  resources:
  - ephemeralapplicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeralapps.toolkit.hinge.com
  resources:
  - ephemeralapplicationsets/finalizers
  verbs:
  - update
- apiGroups:
  - ephemeralapps.toolkit.hinge.com
  resources:
  - ephemeralapplicationsets/status
  verbs:
  - get
  - patch
  - update
